apiVersion: v1
kind: ServiceAccount
metadata:
  name: rosettacloud-backend
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::339712964409:role/rosettacloud-backend-irsa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rosettacloud-backend-lab-manager
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["create", "get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rosettacloud-backend-lab-manager
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: rosettacloud-backend
    namespace: dev
roleRef:
  kind: Role
  name: rosettacloud-backend-lab-manager
  apiGroup: rbac.authorization.k8s.io
