apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosettacloud-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosettacloud-frontend
  template:
    metadata:
      labels:
        app: rosettacloud-frontend
    spec:
      containers:
        - name: rosettacloud-frontend
          image: 339712964409.dkr.ecr.us-east-1.amazonaws.com/rosettacloud-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: rosettacloud-frontend-service
  namespace: dev
spec:
  selector:
    app: rosettacloud-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: ClusterIP
