apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rosettacloud-frontend
  namespace: dev
spec:
  hosts:
    - "dev.rosettacloud.app"
  gateways:
    - rosettacloud-gateway
  http:
    - route:
        - destination:
            host: rosettacloud-frontend-service.dev.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rosettacloud-backend
  namespace: dev
spec:
  hosts:
    - "api.dev.rosettacloud.app"
  gateways:
    - rosettacloud-gateway
  http:
    - route:
        - destination:
            host: rosettacloud-backend-service.dev.svc.cluster.local
            port:
              number: 80
