apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: ingress
spec:
  type: NodePort
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
      protocol: TCP

